name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:

jobs:
  linux_ossl_30:
    name: Linux with OpenSSL 3.0
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libcppunit-dev libssl-dev p11-kit
      - name: Build
        # Once all OpenSSL deprecations fixed, uncomment this
        # env:
        #   CXXFLAGS: -Werror
        run: |
          sudo chmod +x autogen.sh
          ./autogen.sh
          ./configure --with-crypto-backend=openssl
          make
      - name: Test
        run: |
          make check || (find . -name test-suite.log -exec cat {} \; && false)
      - name: Prepare release
        run: |
          tar -cvzf libsofthsm2-${{ matrix.os }}.tgz -C src/lib/.libs libsofthsm2.so
      - name: Stage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux-${{ matrix.os }}
          path: libsofthsm2-${{ matrix.os }}.tgz

  windows:
    name: Windows (${{ matrix.arch }}, ${{ matrix.backend }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            backend: openssl
            target-platform: x64
            build-options:
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Create vcpkg.json
        run: >
          echo '{ "dependencies": [ "openssl", "botan", "cppunit" ],
                  "overrides": [ { "name": "openssl", "version-string": "1.1.1n" },
                                 { "name": "botan",   "version-string": "2.19.3" } ],
                  "builtin-baseline": "38d1652f152d36481f2f4e8a85c0f1e14f3769f7" }' > vcpkg.json
      - uses: seanmiddleditch/vcpkg-action@master
        id: vcpkg
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: ${{ matrix.arch }}-windows
          token: ${{ github.token }}
      - name: Build
        run: |
          mkdir build
          cmake -B build ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -A ${{ matrix.target-platform }} -DWITH_CRYPTO_BACKEND=${{ matrix.backend }} ${{ matrix.build-options }} -DDISABLE_NON_PAGED_MEMORY=ON -DBUILD_TESTS=ON
          cmake --build build
      - name: Test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: |
          cmake --build build --target RUN_TESTS
      - name: Prepare release
        run: |
          tar -cvzf libsofthsm2-win-${{ matrix.arch }}-${{ matrix.backend }}.tgz -C build/src/lib/Debug *.dll
      - name: Stage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-windows-${{ matrix.arch }}-${{ matrix.backend }}
          path: libsofthsm2-win-${{ matrix.arch }}-${{ matrix.backend }}.tgz

  release:
    needs: [linux_ossl_30, windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: binaries-*
          path: dist
          merge-multiple: true # Flattens all 'binaries-*' into the 'dist' folder

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
          name: Release ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }} for ${{ matrix.os }}
          draft: false
          prerelease: ${{ github.event_name == 'pull_request' }} # Mark as prerelease if from a PR
          fail_on_unmatched_files: true
          files: dist/*
          generate_release_notes: true
